/* resourcemap.js generated by blorbtool.py */
StaticImageInfo = {
1: {
  "image": 1, 
  "url": "interpreter/pict-1.png", 
  "width": 960, 
  "height": 720
}
,
3: {
  "image": 3, 
  "url": "interpreter/pict-3.png", 
  "width": 800, 
  "height": 600
}
,
4: {
  "image": 4, 
  "url": "interpreter/pict-4.png", 
  "width": 800, 
  "height": 600
}
,
5: {
  "image": 5, 
  "url": "interpreter/pict-5.png", 
  "width": 554, 
  "height": 468
}
,
6: {
  "image": 6, 
  "url": "interpreter/pict-6.png", 
  "width": 713, 
  "height": 543
}
,
7: {
  "image": 7, 
  "url": "interpreter/pict-7.png", 
  "width": 812, 
  "height": 97
}
,
8: {
  "image": 8, 
  "url": "interpreter/pict-8.png", 
  "width": 192, 
  "height": 80
}
,
9: {
  "image": 9, 
  "url": "interpreter/pict-9.png", 
  "width": 447, 
  "height": 619
}
};
